[project]
name = "gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlx>=0.31.1",
    "numpy>=2.4.3",
    "requests>=2.33.0",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "torchvision>=0.25.0",
    "tqdl>=0.0.4",
]

[dependency-groups]
dev = [
    "torch>=2.10.0",
]
